const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),DK="sqpro_data",PK="sqpro_profiles",SK="sqpro_session";
const key=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,fmt=(k,o={day:"numeric",month:"short"})=>new Intl.DateTimeFormat("de-CH",o).format(new Date(k+"T12:00:00")),esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let profiles=JSON.parse(localStorage.getItem(PK)||"{}"),email=localStorage.getItem(SK)||"",data=load(),mode="focus",duration=1500,left=1500,running=false,timer=null,lastTick=0,partial=0,month=new Date(),selectedDate=key(),taskFilter="all",signup=false;
function fresh(){return{name:"",goal:60,xp:0,total:0,sessions:0,streak:0,best:0,lastDay:"",byDay:{},tasks:[],events:{},plans:[],notes:"",decks:[],activeDeck:null}}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(DK)||"{}"))}catch{return fresh()}}
function save(render=true){localStorage.setItem(DK,JSON.stringify(data));if(render)renderAll()}
function initApp(){if(email&&profiles[email]){data=load();data.name=profiles[email].name||data.name||email.split("@")[0];$("#login").classList.add("hidden");$("#app").classList.remove("hidden");renderAll();go("home")}else{$("#login").classList.remove("hidden");$("#app").classList.add("hidden")}}
$("#switchAuth").onclick=()=>{signup=!signup;$("#nameWrap").classList.toggle("hidden",!signup);$("#authTitle").textContent=signup?"Dein StudyQuest beginnt.":"Dein Fokus beginnt hier.";$("#authDesc").textContent=signup?"Erstelle dein lokales Profil in wenigen Schritten.":"Melde dich an und mach deinen nächsten Schritt.";$("#authSubmit").innerHTML=signup?'Profil erstellen <span>→</span>':'Anmelden <span>→</span>';$("#switchText").textContent=signup?"Du hast schon ein Profil?":"Noch kein Profil?";$("#switchAuth").textContent=signup?"Anmelden":"Konto erstellen";$("#error").textContent=""};
$("#authForm").onsubmit=e=>{e.preventDefault();let em=$("#email").value.trim().toLowerCase(),pass=$("#password").value;let err=$("#error");if(signup){if(profiles[em]){err.textContent="Dieses lokale Profil gibt es bereits. Bitte melde dich an.";return}let name=$("#nameInput").value.trim()||em.split("@")[0];profiles[em]={name};localStorage.setItem(PK,JSON.stringify(profiles));email=em;localStorage.setItem(SK,email);data=fresh();data.name=name;save(false);initApp()}else{if(!profiles[em]){err.textContent="Kein lokales Profil gefunden. Erstelle zuerst ein Profil auf diesem Gerät.";return}email=em;localStorage.setItem(SK,email);data=load();data.name=profiles[em].name;save(false);initApp()}};
function logout(){if(running)stopTimer();localStorage.removeItem(SK);email="";initApp()}
function initials(){return(data.name||email.split("@")[0]||"S").split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function go(p){$$(".page").forEach(x=>x.classList.toggle("active",x.id===p));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));let n={home:"Übersicht",timer:"Fokus-Timer",tasks:"Aufgaben",calendar:"Kalender",planner:"Lernplan",flashcards:"Lernkarten",stats:"Statistik",notes:"Notizen",settings:"Einstellungen"};$("#crumb").textContent=n[p]||p;if(p==="calendar")renderCalendar();if(p==="stats")renderStats();if(p==="planner")renderPlans();if(p==="flashcards")renderFlashcards();if(p==="notes")$("#notesText").value=data.notes}
$$(".nav[data-page]").forEach(b=>b.onclick=()=>go(b.dataset.page));
function addMinute(){let k=key();data.total++;data.xp++;data.byDay[k]=(data.byDay[k]||0)+1;if(data.lastDay!==k){let y=new Date();y.setDate(y.getDate()-1);data.streak=data.lastDay===key(y)?data.streak+1:1;data.best=Math.max(data.best,data.streak);data.lastDay=k}localStorage.setItem(DK,JSON.stringify(data));renderAll(false)}
function renderAll(clock=true){let today=data.byDay[key()]||0,done=data.tasks.filter(t=>t.done).length,open=data.tasks.filter(t=>!t.done).length,level=Math.floor(data.xp/250)+1,pct=Math.min(100,Math.round(today/Math.max(1,data.goal)*100));$("#profileName").textContent=data.name||"Study friend";$("#profileEmail").textContent=email;$("#initial").textContent=initials();$("#topInitial").textContent=initials();$("#greeting").innerHTML=`${new Date().getHours()<11?"Guten Morgen":new Date().getHours()<18?"Hallo":"Guten Abend"}, <span>${esc(data.name||"schön, dass du da bist")} <em>✦</em></span>`;$("#dateLine").textContent=new Intl.DateTimeFormat("de-CH",{weekday:"long",day:"numeric",month:"long"}).format(new Date()).toUpperCase();$("#todayLabel").textContent=fmt(key(),{weekday:"short",day:"numeric",month:"short"});$("#level").textContent="Level "+level;$("#xp").textContent=data.xp+" XP";$("#heroMinutes").textContent=today;$("#goalNow").textContent=today;$("#goalTarget").textContent=data.goal;$("#goalBar").style.width=pct+"%";$("#goalPct").textContent=pct+"%";$("#goalMessage").textContent=pct>=100?"Tagesziel geschafft — stark!":"Du bist auf deinem Weg.";$("#minutes").innerHTML=`${today} <small>min</small>`;$("#tasksStat").innerHTML=`${done} <small>/ ${data.tasks.length}</small>`;$("#taskBar").style.width=(data.tasks.length?done/data.tasks.length*100:0)+"%";$("#streak").innerHTML=`${data.streak} <small>Tage</small>`;$("#taskCount").textContent=open;$("#minBars").innerHTML=Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-6+i);return `<i style="height:${Math.max(4,Math.min(35,(data.byDay[key(d)]||0)/Math.max(30,data.goal)*35))}px"></i>`}).join("");$("#streakDots").innerHTML=Array.from({length:7},(_,i)=>`<i class="${i<data.streak%8?"on":""}"></i>`).join("");renderTaskLists();renderUpcoming();$("#timerToday").textContent=today+" min";$("#timerXP").textContent=data.xp+" XP";$("#settingsName").value=data.name;$("#settingsGoal").value=data.goal;$("#notesText").value=data.notes;if(clock)drawClock()}
function addTask(){let title=prompt("Was möchtest du erledigen?");if(!title?.trim())return;let subject=prompt("Fach oder Kategorie:","Schule")||"Allgemein",date=prompt("Fällig am (JJJJ-MM-TT):",key())||key();data.tasks.push({id:Date.now(),title:title.trim(),subject,date,done:false});save()}
function toggleTask(id){let t=data.tasks.find(t=>t.id===id);if(!t)return;t.done=!t.done;data.xp=Math.max(0,data.xp+(t.done?10:-10));save()}
function delTask(id){if(confirm("Aufgabe löschen?")){data.tasks=data.tasks.filter(t=>t.id!==id);save()}}
function taskHTML(arr){return arr.map(t=>`<div class="taskrow ${t.done?"done":""}"><button class="check ${t.done?"checked":""}" onclick="toggleTask(${t.id})">${t.done?"✓":""}</button><div class="taskcopy"><b>${esc(t.title)}</b><small>${esc(t.subject)} · ${t.date}</small></div><span class="tasktag">${t.done?"ERLEDIGT":t.date===key()?"HEUTE":""}</span><button class="xbtn" onclick="delTask(${t.id})">×</button></div>`).join("")||'<div class="empty"><b>Alles im Blick ✦</b><p>Hier ist noch nichts eingetragen.</p></div>'}
function renderTaskLists(){$("#homeTasks").innerHTML=taskHTML(data.tasks.filter(t=>!t.done).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4));$("#allTasks").innerHTML=taskHTML(data.tasks.filter(t=>taskFilter==="all"||(taskFilter==="open"&&!t.done)||(taskFilter==="done"&&t.done)).sort((a,b)=>a.date.localeCompare(b.date)))}
function filterTasks(f,b){taskFilter=f;$$(".filters button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");renderTaskLists()}
function addEventPrompt(day=selectedDate){let title=prompt("Wie heisst der Termin?");if(!title?.trim())return;let date=prompt("Datum (JJJJ-MM-TT):",day||key());if(!date||!/^\d{4}-\d{2}-\d{2}$/.test(date))return alert("Datum bitte als JJJJ-MM-TT eingeben.");let type=(prompt("Kategorie: schule, prüfung, privat oder training","schule")||"schule").toLowerCase(),time=prompt("Uhrzeit (optional, z. B. 14:30):","");(data.events[date]??=[]).push({id:Date.now(),title:title.trim(),type,time});save();renderCalendar()}
function removeEvent(day,id){data.events[day]=(data.events[day]||[]).filter(e=>e.id!==id);if(!data.events[day].length)delete data.events[day];save();renderCalendar()}
function colorClass(t){return t==="prüfung"?"peachdot":t==="privat"?"mintdot":t==="training"?"bluedot":"purpled"}
function renderUpcoming(){let list=Object.entries(data.events).flatMap(([day,es])=>es.map(e=>({...e,day}))).filter(e=>e.day>=key()).sort((a,b)=>(a.day+a.time).localeCompare(b.day+b.time)).slice(0,4);$("#upcoming").innerHTML=list.map(e=>`<div class="upcoming"><div class="update"><b>${new Date(e.day+"T12:00:00").getDate()}</b><small>${fmt(e.day,{month:"short"})}</small></div><div class="upcopy"><b>${esc(e.title)}</b><small>${e.time?esc(e.time)+" · ":""}${esc(e.type)}</small></div><i class="dot ${colorClass(e.type)}"></i></div>`).join("")||'<div class="empty"><p>Keine Termine geplant.</p></div>'}
function changeMonth(n){month.setMonth(month.getMonth()+n);renderCalendar()}function goToday(){month=new Date();selectedDate=key();renderCalendar()}function selectDay(k){selectedDate=k;renderCalendar()}
function renderCalendar(){let y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),off=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate();$("#monthTitle").textContent=new Intl.DateTimeFormat("de-CH",{month:"long",year:"numeric"}).format(month);let h=["Mo","Di","Mi","Do","Fr","Sa","So"].map(d=>`<div class="weekday">${d}</div>`).join("");for(let i=0;i<off;i++)h+='<div class="blankday"></div>';for(let n=1;n<=last;n++){let k=`${y}-${String(m+1).padStart(2,"0")}-${String(n).padStart(2,"0")}`,ev=data.events[k]||[];h+=`<button class="calday ${k===key()?"istoday":""} ${k===selectedDate?"isselected":""}" onclick="selectDay('${k}')"><b>${n}</b><span>${ev.slice(0,3).map(e=>`<i class="dot ${colorClass(e.type)}"></i>`).join("")}</span>${ev.length?`<small>${esc(ev[0].title)}</small>`:""}</button>`}$("#calendarGrid").innerHTML=h;let ev=data.events[selectedDate]||[];$("#dayTitle").textContent=fmt(selectedDate,{weekday:"long",day:"numeric",month:"long"});$("#dayEvents").innerHTML=ev.map(e=>`<div class="dayevent"><i class="dot ${colorClass(e.type)}"></i><div><b>${esc(e.title)}</b><small>${e.time?esc(e.time)+" · ":""}${esc(e.type)}</small></div><button onclick="removeEvent('${selectedDate}',${e.id})">×</button></div>`).join("")||'<div class="empty"><p>Für diesen Tag ist noch nichts geplant.</p></div>'}
function addPlan(){let text=prompt("Was möchtest du lernen oder planen?");if(!text?.trim())return;let date=prompt("Datum (JJJJ-MM-TT):",key())||key();data.plans.push({id:Date.now(),text:text.trim(),date});save()}
function delPlan(id){data.plans=data.plans.filter(p=>p.id!==id);save()}
function renderPlans(){$("#planList").innerHTML=data.plans.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(p=>`<div class="planrow"><div class="update"><b>${new Date(p.date+"T12:00:00").getDate()}</b><small>${fmt(p.date,{month:"short"})}</small></div><div class="taskcopy"><b>${esc(p.text)}</b><small>${p.date}</small></div><button class="xbtn" onclick="delPlan(${p.id})">×</button></div>`).join("")||'<div class="empty"><b>Dein Plan wartet auf dich.</b><p>Füge einen Lernschritt hinzu.</p></div>'}
function setMode(min,m,b){if(running)stopTimer();mode=m;duration=min*60;left=duration;partial=0;$$(".modes button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("#modeLabel").textContent=m==="focus"?"TIME TO FOCUS":"TAKE A BREATH";$("#timerSub").textContent=m==="focus"?"Du schaffst das.":"Eine kurze Pause tut gut.";drawClock()}
function drawClock(){let mm=Math.floor(left/60),ss=Math.floor(left%60);$("#clock").textContent=`${String(mm).padStart(2,"0")}:${String(ss).padStart(2,"0")}`;let c=2*Math.PI*112;$("#arc").style.strokeDasharray=c;$("#arc").style.strokeDashoffset=c*(1-left/duration);$("#timerStart").textContent=running?"Ⅱ Pause":left<duration?"▶ Weiter":"▶ Start"}
function toggleTimer(){if(running){stopTimer();return}running=true;lastTick=Date.now();timer=setInterval(tick,200);drawClock()}
function tick(){let now=Date.now(),delta=(now-lastTick)/1000;lastTick=now;left=Math.max(0,left-delta);if(mode==="focus"){partial+=delta;while(partial>=60){partial-=60;addMinute()}}drawClock();if(left<=0){clearInterval(timer);running=false;if(mode==="focus"){data.xp+=5;data.sessions++;localStorage.setItem(DK,JSON.stringify(data));renderAll(false);$("#timerSub").textContent="Session geschafft! +5 Bonus-XP ✦"}else $("#timerSub").textContent="Pause vorbei — bereit?";partial=0;drawClock()}}
function stopTimer(){clearInterval(timer);running=false;drawClock()}function resetTimer(){if(running)stopTimer();left=duration;partial=0;drawClock()}
function renderStats(){let today=new Date(),vals=Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-6+i);return{label:new Intl.DateTimeFormat("de-CH",{weekday:"short"}).format(d),v:data.byDay[key(d)]||0}}),max=Math.max(30,...vals.map(x=>x.v));$("#allMinutes").innerHTML=`${data.total} <small>min</small>`;$("#allXP").textContent=data.xp;$("#allSessions").textContent=data.sessions;$("#chart").innerHTML=vals.map(x=>`<div class="chartcol"><b>${x.v}</b><div class="barwrap"><i style="height:${Math.max(4,x.v/max*100)}%"></i></div><small>${x.label}</small></div>`).join("");let ach=[["✦","Erste Lernminute",data.total>=1],["◷","Eine Stunde Fokus",data.total>=60],["☑","Erste Aufgabe",data.tasks.some(t=>t.done)],["🔥","Drei Tage Streak",data.best>=3],["⭐","Level 5",Math.floor(data.xp/250)+1>=5],["◎","Tagesziel erreicht",(data.byDay[key()]||0)>=data.goal]];$("#achievements").innerHTML=ach.map(a=>`<div class="achievement ${a[2]?"unlocked":""}"><span>${a[0]}</span><b>${a[1]}</b><small>${a[2]?"Freigeschaltet":"Noch gesperrt"}</small></div>`).join("")}
$("#notesText").oninput=()=>{data.notes=$("#notesText").value;localStorage.setItem(DK,JSON.stringify(data));$("#saved").textContent="Gespeichert ✓";setTimeout(()=>$("#saved").textContent="Wird automatisch gespeichert",1000)};
function saveSettings(){data.name=$("#settingsName").value.trim()||"Study friend";data.goal=Math.max(5,Math.min(600,+$("#settingsGoal").value||60));if(profiles[email]){profiles[email].name=data.name;localStorage.setItem(PK,JSON.stringify(profiles))}save();alert("Einstellungen gespeichert ✓")}
function exportData(){let a=document.createElement("a"),blob=new Blob([JSON.stringify({data,profile:profiles[email]},null,2)],{type:"application/json"});a.href=URL.createObjectURL(blob);a.download="studyquest-sicherung.json";a.click();URL.revokeObjectURL(a.href)}
function importData(){let i=document.createElement("input");i.type="file";i.accept=".json,application/json";i.onchange=async()=>{try{let o=JSON.parse(await i.files[0].text());if(!o.data)throw 0;data=Object.assign(fresh(),o.data);save();alert("Sicherung importiert ✓")}catch{alert("Sicherungsdatei konnte nicht gelesen werden.")}};i.click()}
function resetData(){if(confirm("Alle Lerndaten und Termine löschen?")){data=fresh();data.name=profiles[email]?.name||"";save()}}

function createDeckPrompt(){let name=prompt("Wie soll dein Lernkarten-Stapel heissen?");if(!name?.trim())return;let subject=prompt("Fach oder Thema:","Französisch")||"Allgemein";let d={id:Date.now(),name:name.trim(),subject,cards:[]};data.decks.push(d);data.activeDeck=d.id;save();go("flashcards")}
function getDeck(){return data.decks.find(d=>d.id===data.activeDeck)||data.decks[0]||null}
function createCardPrompt(){let d=getDeck();if(!d){createDeckPrompt();return}let q=prompt("Frage / Vorderseite der Karte:");if(!q?.trim())return;let a=prompt("Antwort / Rückseite der Karte:");if(!a?.trim())return;d.cards.push({id:Date.now(),q:q.trim(),a:a.trim(),mastered:false,seen:0});studyIndex=Math.max(0,d.cards.length-1);flipped=false;save();go("flashcards")}
let studyIndex=0,flipped=false;
function selectDeck(id){data.activeDeck=id;studyIndex=0;flipped=false;save();renderFlashcards()}
function deleteDeck(id){let d=data.decks.find(x=>x.id===id);if(!d)return;if(!confirm(`Stapel „${d.name}“ mit allen Karten löschen?`))return;data.decks=data.decks.filter(x=>x.id!==id);if(data.activeDeck===id)data.activeDeck=data.decks[0]?.id||null;studyIndex=0;save();renderFlashcards()}
function editCard(id){let d=getDeck(),c=d?.cards.find(x=>x.id===id);if(!c)return;let q=prompt("Frage bearbeiten:",c.q);if(q===null)return;let a=prompt("Antwort bearbeiten:",c.a);if(a===null)return;c.q=q.trim()||c.q;c.a=a.trim()||c.a;save();renderFlashcards()}
function deleteCard(id){let d=getDeck();if(!d||!confirm("Diese Lernkarte löschen?"))return;d.cards=d.cards.filter(c=>c.id!==id);studyIndex=Math.min(studyIndex,Math.max(0,d.cards.length-1));flipped=false;save();renderFlashcards()}
function flipCard(){let d=getDeck();if(!d?.cards.length)return;flipped=!flipped;renderStudyCard()}
function nextCard(){let d=getDeck();if(!d?.cards.length)return;studyIndex=(studyIndex+1)%d.cards.length;flipped=false;renderStudyCard()}
function previousCard(){let d=getDeck();if(!d?.cards.length)return;studyIndex=(studyIndex-1+d.cards.length)%d.cards.length;flipped=false;renderStudyCard()}
function rateCard(known){let d=getDeck(),c=d?.cards[studyIndex];if(!c)return;c.seen=(c.seen||0)+1;if(known&&!c.mastered){c.mastered=true;data.xp+=1}else if(!known){c.mastered=false}save(false);nextCard();renderFlashcards()}
function renderStudyCard(){let d=getDeck(),fc=$("#flashcard");if(!d||!d.cards.length){$("#studyDeckTitle").textContent=d?.name||"Wähle einen Stapel";$("#cardCounter").textContent="0 / 0";fc.className="flashcard emptyflash";fc.innerHTML='<div><span class="flashsymbol">✦</span><h3>Noch keine Karten</h3><p>Füge deinem Stapel deine erste Frage hinzu.</p></div>';$("#studyControls").classList.add("hidden");$("#ratingControls").classList.add("hidden");$("#deckMastered").textContent="0";return}let c=d.cards[studyIndex];$("#studyDeckTitle").textContent=d.name;$("#cardCounter").textContent=`${studyIndex+1} / ${d.cards.length}`;fc.className="flashcard "+(flipped?"flipped":"");fc.innerHTML=`<small>${flipped?"ANTWORT":"FRAGE"} · ${esc(d.subject)}</small><div class="flashcontent">${esc(flipped?c.a:c.q).replace(/\n/g,"<br>")}</div><span class="flipnote">${flipped?"Gut gemacht — bewerte, wie sicher du warst.":"Denk kurz nach und zeig dann die Antwort."}</span>`;$("#studyControls").classList.remove("hidden");$("#ratingControls").classList.toggle("hidden",!flipped);$("#flipButton").textContent=flipped?"Frage ansehen ↻":"Antwort zeigen ↻";$("#deckMastered").textContent=d.cards.filter(x=>x.mastered).length}
function renderFlashcards(){if(!$("#deckList"))return;let d=getDeck();$("#deckList").innerHTML=data.decks.map(x=>`<div class="deckrow ${x.id===d?.id?"active":""}"><button class="deckselect" onclick="selectDeck(${x.id})"><span class="deckicon">▣</span><span class="deckcopy"><b>${esc(x.name)}</b><small>${esc(x.subject)} · ${x.cards.length} Karten</small></span><span class="deckprogress">${x.cards.filter(c=>c.mastered).length}/${x.cards.length}</span></button><button class="xbtn" title="Stapel löschen" onclick="deleteDeck(${x.id})">×</button></div>`).join("")||'<div class="empty"><b>Hier entstehen deine Lernstapel.</b><p>Lege z. B. einen Stapel für Französisch-Voci an.</p></div>';$("#libraryTitle").textContent=d?`Kartenübersicht · ${d.name}`:"Kartenübersicht";$("#cardLibrary").innerHTML=d?.cards.length?d.cards.map((c,i)=>`<div class="libraryrow"><span class="libnum">${String(i+1).padStart(2,"0")}</span><div class="libcopy"><b>${esc(c.q)}</b><small>${esc(c.a)}</small></div><span class="masterbadge ${c.mastered?"isdone":""}">${c.mastered?"✓ Sicher":"Offen"}</span><button class="xbtn" onclick="editCard(${c.id})" title="Bearbeiten">✎</button><button class="xbtn" onclick="deleteCard(${c.id})" title="Löschen">×</button></div>`).join(""):'<div class="empty"><p>Dieser Stapel hat noch keine Karten.</p></div>';renderStudyCard()}

initApp();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
